apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-tilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfo-tilgangskontroll/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfo-tilgangskontroll/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfo-tilgangskontroll/internal/prometheus
  ingresses:
    - "https://syfo-tilgangskontroll.nais.adeo.no"
    - "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - "https://syfo-tilgangskontroll.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ispengestopp
          namespace: teamsykefravr
          cluster: prod-fss
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: prod-fss
        - application: isprediksjon
          namespace: teamsykefravr
          cluster: prod-fss
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: prod-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-fss
        - application: modiasyforest
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomoteadmin
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfoperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
        - application: spinnsyn-backend
          namespace: flex
          cluster: prod-gcp
        - application: syfosoknad
          namespace: flex
          cluster: prod-fss
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-fss
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: prod-fss
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/syfo-tilgangskontroll
        mountPath: /var/run/secrets/nais.io/azuread
      - kvPath: "/serviceuser/data/prod/srvsyfo-tilgangskontroll"
        mountPath: "/secrets/serviceuser/syfo-tilgangskontroll"
      - kvPath: serviceuser/data/prod/srvssolinux
        mountPath: /secrets/ldap/ldap
      - kvPath: /kv/prod/fss/syfo-tilgangskontroll/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "syfo-tilgangskontroll"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: AAD_TENANT_ID
      value: 62366534-1ec3-4962-8869-9b5535279d0b
    - name: SMREGISTRERING_CLIENT_ID
      value: "88adf8ed-fed1-4022-bbc6-da222e4795eb"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_DISCOVERYURL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_ACCEPTEDAUDIENCE
      value: dfaa2699-7390-4459-9cfc-2e8de64dfaf9,5d54801d-b01e-405c-9062-a55287c4931d
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_BASEDN
      value: dc=adeo,dc=no
    - name: AXSYS_URL
      value: "https://axsys.nais.adeo.no"
    - name: NORG2_URL
      value: https://app.adeo.no/norg2
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no/graphql"
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no
    - name: SYFOBEHANDLENDEENHET_URL
      value: https://syfobehandlendeenhet.nais.adeo.no
