apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-tilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /syfo-tilgangskontroll/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfo-tilgangskontroll/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfo-tilgangskontroll/internal/prometheus
  ingresses:
    - "https://syfo-tilgangskontroll.nais.adeo.no"
    - "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - "https://syfo-tilgangskontroll.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ispengestopp
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: prod-fss
        - application: isprediksjon
          namespace: teamsykefravr
          cluster: prod-fss
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: prod-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomoteadmin
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfoperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
        - application: spinnsyn-backend
          namespace: flex
          cluster: prod-gcp
        - application: syfosoknad
          namespace: flex
          cluster: prod-fss
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-fss
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: prod-fss
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvssolinux
        mountPath: /secrets/ldap/ldap
      - kvPath: /kv/prod/fss/syfo-tilgangskontroll/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "syfo-tilgangskontroll"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: SMREGISTRERING_CLIENT_ID
      value: "7dbaa882-8730-4ed2-97fb-42ca08b7ea29"
    - name: LDAP_URL
      value: ldaps://ldapgw.adeo.no
    - name: LDAP_BASEDN
      value: dc=adeo,dc=no
    - name: AXSYS_URL
      value: "https://axsys.nais.adeo.no"
    - name: GRAPHAPI_URL
      value: "https://graph.microsoft.com"
    - name: NORG2_URL
      value: https://app.adeo.no/norg2
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.intern.nav.no"

    - name: ROLE_KODE6_ID
      value: "c3c01903-38b8-4cf5-b551-65cd3479dea4" # 0000-GA-GOSYS_KODE6
    - name: ROLE_KODE7_ID
      value: "cd001e5e-ce26-44aa-b79e-fca780a2414b" # 0000-GA-GOSYS_KODE7
    - name: ROLE_SYFO_ID
      value: "100e88eb-79af-4136-8bfe-f79b32021f43" # 0000-GA-SYFO-SENSITIV
    - name: ROLE_SKJERMING_ID
      value: "73ff0e76-f2b1-4586-8387-b33f15617381" # 0000-GA-GOSYS_UTVIDET
    - name: ROLE_NASJONAL_ID
      value: "3063daf5-24c6-409c-9139-2d843cb4327b" # 0000-GA-GOSYS_NASJONAL
    - name: ROLE_UTVIDBAR_NASJONAL_ID
      value: "ad3ee064-44b7-4c58-a618-5df1e1cb05db" # 0000-GA-GOSYS_UTVIDBAR_TIL_NASJONAL
    - name: ROLE_REGIONAL_ID
      value: "422852aa-aad5-4601-a8c8-917ef42b6601" # 0000-GA-GOSYS_REGIONAL
    - name: ROLE_UTVIDBAR_REGIONAL_ID
      value: "14caf09e-dd9a-43fe-b25e-7f58dd9fdcae" # 0000-GA-GOSYS_UTVIDBAR_TIL_REGIONAL
