apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-tilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfo-tilgangskontroll/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfo-tilgangskontroll/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfo-tilgangskontroll/internal/prometheus
  ingresses:
    - "https://syfo-tilgangskontroll.nais.preprod.local"
    - "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
    - "https://syfo-tilgangskontroll.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: ispengestopp
          namespace: teamsykefravr
          cluster: dev-fss
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: dev-fss
        - application: isprediksjon
          namespace: teamsykefravr
          cluster: dev-fss
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: dev-fss
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomoteadmin
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfoperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: spinnsyn-backend
          namespace: flex
          cluster: dev-gcp
        - application: syfosoknad
          namespace: flex
          cluster: dev-fss
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: dev-fss
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: dev-fss
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/syfo-tilgangskontroll
        mountPath: /var/run/secrets/nais.io/azuread
      - kvPath: serviceuser/data/dev/srvssolinux
        mountPath: /secrets/ldap/ldap
      - kvPath: /kv/preprod/fss/syfo-tilgangskontroll/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "syfo-tilgangskontroll"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: AAD_TENANT_ID
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: SMREGISTRERING_CLIENT_ID
      value: "3936bfbe-f658-4eab-a0e4-0222fc730d67"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_ACCEPTEDAUDIENCE
      value: 32e36aa5-1d12-452a-9b1e-9f3f557cbb4d,edd82db3-6e00-476c-8b9a-cf4ad8e2ab46
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: AXSYS_URL
      value: "https://axsys.nais.preprod.local"
    - name: NORG2_URL
      value: https://app-q1.adeo.no/norg2
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev.intern.nav.no/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: https://syfobehandlendeenhet.nais.preprod.local
