apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-tilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /syfo-tilgangskontroll/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfo-tilgangskontroll/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfo-tilgangskontroll/internal/prometheus
  ingresses:
    - "https://syfo-tilgangskontroll.nais.adeo.no"
    - "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - "https://syfo-tilgangskontroll.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isdialogmotekandidat
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ispengestopp
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfoperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
        - application: spinnsyn-backend
          namespace: flex
          cluster: prod-gcp
        - application: sykepengesoknad-backend
          namespace: flex
          cluster: prod-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syk-dig-backend
          namespace: teamsykmelding
          cluster: prod-gcp
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/syfo-tilgangskontroll/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: FASTLEGEREST_CLIENT_ID
      value: "b1df05b6-427f-4a95-897d-a491cf34f4e0"
    - name: FINNFASTLEGE_CLIENT_ID
      value: "916a8191-f241-4227-be1a-4b820657254f"
    - name: ISDIALOGMOTE_CLIENT_ID
      value: "4898e614-e73d-4067-aafd-5afc2254c6b6"
    - name: ISDIALOGMELDING_CLIENT_ID
      value: "be3df271-2897-4b64-9ed9-41eee3d85d7c"
    - name: ISDIALOGMOTEKANDIDAT_CLIENT_ID
      value: "11a9b0b1-9eaf-41ea-9e3b-b29452699d7f"
    - name: ISNARMESTELEDER_CLIENT_ID
      value: "919349b5-e9e5-4fe0-a2f0-af90f013d8e5"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "8af04bfe-8ebc-4fd1-818e-bf18967bc114"
    - name: ISPENGESTOPP_CLIENT_ID
      value: "99984ce1-1b1a-465e-834b-61d85151c7fb"
    - name: ISPERSONOPPGAVE_CLIENT_ID
      value: "d15032c0-c943-4a4b-bc44-110329265f5e"
    - name: SMREGISTRERING_CLIENT_ID
      value: "7dbaa882-8730-4ed2-97fb-42ca08b7ea29"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "43b7c701-08ea-4f8d-91e0-1ad630d7248b"
    - name: SYFOMODIAPERSON_CLIENT_ID
      value: "a04bb3b5-8051-40bb-a5f0-f9f4a409b07a"
    - name: SYFOOVERSIKTSRV_CLIENT_ID
      value: "0ff9c36d-d1a0-4e03-8ab6-913d1ba8fcbd"
    - name: SYFOPERSON_CLIENT_ID
      value: "036e5cf4-7381-454e-8f73-33a0a47d9902"
    - name: AXSYS_URL
      value: "https://axsys.nais.adeo.no"
    - name: GRAPHAPI_URL
      value: "https://graph.microsoft.com"
    - name: NORG2_URL
      value: https://app.adeo.no/norg2
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.intern.nav.no"

    - name: ROLE_KODE6_ID
      value: "c3c01903-38b8-4cf5-b551-65cd3479dea4" # 0000-GA-GOSYS_KODE6
    - name: ROLE_KODE7_ID
      value: "cd001e5e-ce26-44aa-b79e-fca780a2414b" # 0000-GA-GOSYS_KODE7
    - name: ROLE_SYFO_ID
      value: "100e88eb-79af-4136-8bfe-f79b32021f43" # 0000-GA-SYFO-SENSITIV
    - name: ROLE_SKJERMING_ID
      value: "73ff0e76-f2b1-4586-8387-b33f15617381" # 0000-GA-GOSYS_UTVIDET
    - name: ROLE_NASJONAL_ID
      value: "3063daf5-24c6-409c-9139-2d843cb4327b" # 0000-GA-GOSYS_NASJONAL
    - name: ROLE_UTVIDBAR_NASJONAL_ID
      value: "ad3ee064-44b7-4c58-a618-5df1e1cb05db" # 0000-GA-GOSYS_UTVIDBAR_TIL_NASJONAL
    - name: ROLE_REGIONAL_ID
      value: "422852aa-aad5-4601-a8c8-917ef42b6601" # 0000-GA-GOSYS_REGIONAL
    - name: ROLE_UTVIDBAR_REGIONAL_ID
      value: "14caf09e-dd9a-43fe-b25e-7f58dd9fdcae" # 0000-GA-GOSYS_UTVIDBAR_TIL_REGIONAL
    - name: ROLE_PAPIRSYKMELDING_ID
      value: "dfde2123-1969-4cd2-8977-bdf19721e76d" # 0000-GA-papirsykmelding
