apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-tilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /syfo-tilgangskontroll/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfo-tilgangskontroll/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfo-tilgangskontroll/internal/prometheus
  ingresses:
    - "https://syfo-tilgangskontroll.nais.preprod.local"
    - "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
    - "https://syfo-tilgangskontroll.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isdialogmotekandidat
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: ispengestopp
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: ispersonoppgave
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversiktsrv
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfoperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: spinnsyn-backend
          namespace: flex
          cluster: dev-gcp
        - application: sykepengesoknad-backend
          namespace: flex
          cluster: dev-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syk-dig-backend
          namespace: teamsykmelding
          cluster: dev-gcp
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/syfo-tilgangskontroll/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: FASTLEGEREST_CLIENT_ID
      value: "d4a68146-157c-4bde-8afd-494572e819e8"
    - name: FINNFASTLEGE_CLIENT_ID
      value: "decdb625-ddde-4c4a-9586-f20862b9e1fe"
    - name: ISDIALOGMOTE_CLIENT_ID
      value: "1705435b-f7e7-49d6-9fae-89375f28d68f"
    - name: ISDIALOGMELDING_CLIENT_ID
      value: "9201731a-9c36-44b7-a434-721d7c5c9d75"
    - name: ISDIALOGMOTEKANDIDAT_CLIENT_ID
      value: "16f01ef2-84ba-4526-85f9-e25f566be4f6"
    - name: ISNARMESTELEDER_CLIENT_ID
      value: "138e4b6f-cae0-4a3f-a80d-4c7f51680889"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "913b86fe-51cd-4470-9c67-67486f30a326"
    - name: ISPENGESTOPP_CLIENT_ID
      value: "fb9fa715-4a8b-4aca-a818-ae5b8c7dae78"
    - name: ISPERSONOPPGAVE_CLIENT_ID
      value: "fd8a7c4e-db4e-4769-bf76-936d0d9ae686"
    - name: SMREGISTRERING_CLIENT_ID
      value: "3936bfbe-f658-4eab-a0e4-0222fc730d67"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "75922276-00e5-4a90-a6df-2b76d4204cd1"
    - name: SYFOMODIAPERSON_CLIENT_ID
      value: "897256b4-faa4-474a-aa2e-5f7b5b9c7e16"
    - name: SYFOOVERSIKTSRV_CLIENT_ID
      value: "4a6db220-1a94-4453-a3a7-6a1b4904720b"
    - name: SYFOPERSON_CLIENT_ID
      value: "096d3198-c44e-449b-97a9-4bcecc31afa6"
    - name: AXSYS_URL
      value: "https://axsys.nais.preprod.local"
    - name: GRAPHAPI_URL
      value: "https://graph.microsoft.com"
    - name: NORG2_URL
      value: https://app-q1.adeo.no/norg2
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev.intern.nav.no/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.dev.intern.nav.no"

    - name: ROLE_KODE6_ID
      value: "87ea7c87-08a2-43bc-83d6-0bfeee92185d" # 0000-GA-GOSYS_KODE6
    - name: ROLE_KODE7_ID
      value: "69d4a70f-1c83-42a8-8fb8-2f5d54048647" # 0000-GA-GOSYS_KODE7
    - name: ROLE_SYFO_ID
      value: "c8957e0a-909c-4b62-8e11-93aae6d295e6" # 0000-GA-SYFO-SENSITIV
    - name: ROLE_SKJERMING_ID
      value: "de44052d-b062-4497-89a2-0c85b935b808" # 0000-GA-GOSYS_UTVIDET
    - name: ROLE_NASJONAL_ID
      value: "924badcd-b936-44f4-b7bf-97c03de0893a" # 0000-GA-GOSYS_NASJONAL
    - name: ROLE_UTVIDBAR_NASJONAL_ID
      value: "2ffe3262-6c0e-44f3-94f0-34dfa5659a04" # 0000-GA-GOSYS_UTVIDBAR_TIL_NASJONAL
    - name: ROLE_REGIONAL_ID
      value: "d2987104-63b2-4110-83ac-20ff6afe24a2" # 0000-GA-GOSYS_REGIONAL
    - name: ROLE_UTVIDBAR_REGIONAL_ID
      value: "a5c2370e-6b3d-4c2c-9a5e-238008526574" # 0000-GA-GOSYS_UTVIDBAR_TIL_REGIONAL
    - name: ROLE_PAPIRSYKMELDING_ID
      value: "16aff429-1efc-402a-ae12-4000633d0063" # 0000-GA-papirsykmelding
