apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: syfo-tilgangskontroll-redis
spec:
  image: redis:5-alpine
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
