apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: syfo-tilgangskontroll-redis
spec:
  image: redis:5-alpine
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
  accessPolicy:
    inbound:
      rules:
        - application: syfo-tilgangskontroll
        - application: syfo-tilgangskontroll-redisexporter
---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykefravr
  name: syfo-tilgangskontroll-redisexporter
  namespace: teamsykefravr
spec:
  image: oliver006/redis_exporter:latest
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  env:
    - name: REDIS_ADDR
      value: syfo-tilgangskontroll-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  accessPolicy:
    outbound:
      rules:
        - application: syfo-tilgangskontroll-redis
