spring:
  main.banner-mode: 'off'
  cache.type: redis
  redis:
    host: syfo-tilgangskontroll-redis
    port: 6379

no.nav.security.jwt:
  issuer:
    veilederaad:
      discoveryurl: <nais-manifest>
      accepted_audience: <nais-manifest>
      cookiename: ID_token

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfo-tilgangskontroll
