spring:
  main.banner-mode: 'off'
  cache:
      type: none

no.nav.security.oidc:
  issuers: intern,veileder
  issuer:
    intern:
      discoveryurl: <syfonais>
      accepted_audience: modiabrukerdialog-p,modiabrukerdialog-q1,veilarblogin-p,veilarblogin-q1,fpsak-frontend-p,fpsak-frontend-q1,fplos-p,fplos-q1
      cookie_name: ID_token
    veileder:
      discoveryurl: <syfonais>
      accepted_audience: <syfonais>
      cookie_name: isso-idtoken
    veilederaad:
      discoveryurl: <syfonais>
      accepted_audience: <syfonais>
      cookie_name: ID_token

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfo-tilgangskontroll
