name: Deploy redis to NAIS
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/redis.yaml'
      - '.nais/redis-config.yaml'
jobs:
  apply-redis:
    name: Apply Redis cache to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/redis-config.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/redis-config.yaml
